### ISSUE TITLE
'UmiTemplateLibrary' is not defined

### ISSUE THREAD

**Issue by FarzadHashemi88** [samuelduchesne/archetypal#104]
I am trying to convert an E+ idf file to UMI .json template. I am a new Python user and followed the installation instruction (installing using pip) in Python 3.6. I have installed archetypal successfully, but when I am trying to convert the IDF file following "Using the Python Console" I am getting this error: 'UmiTemplateLibrary' is not defined". Please see the attached screenshot from Python IDE.
![Error](https://user-images.githubusercontent.com/34173991/87209749-09703480-c2e1-11ea-9fdb-1791014182b2.JPG)
Please help to figure this problem out!

Thanks,

**Comment by samuelduchesne** [comment]
Hi there! Thanks for trying out archetypal! I think you need to import UmiTemplate instead of UmiTemplateLibrary. I believe the documentation is showing the develop branch instead of the master branch.

I’ll try and fix that. You can also star the repo since I’ll be releasing a much better version in the coming days with a bunch of fixes. It will also change some of the function names. 

Best,

Sam

**Comment by FarzadHashemi88** [comment]
Dear Samuel,

I appreciate your reply!

I am trying to convert a bunch of IDF files to UMI (.json) templateS and I
only found Archetypal something that can help me. I spent some hours
figuring out how to add it to Command Prompt also my Python 3.6 Shell.
However, two methods asserted on the Archetypal
<https://archetypal.readthedocs.io/en/develop/converting.html> are not
giving me what I desire to. Using the "*reduce"* command is giving me the
attached error. Also, using the Python Console and what you suggested to
change UmiTemplateLibrary to UmiTemplate in the syntax didn't work out
properly. I would really appreciate it if you could guide me in a way (as a
beginner Python user) that I can convert my files because this step is
critical to my research.

Regards,
Farzad

**Comment by samuelduchesne** [comment]
Which attached error?
