### ISSUE TITLE
Adjacency errors

### ISSUE THREAD

**Issue by louisleroy5** [samuelduchesne/archetypal#11]
For some buildings, we encounter an "adjacency" error ("adjacent wall not found" in TRNBuild) only for some adjacent wall. Not all adjacent wall are not found.
For example when translating "NECB - Warehouse.idf", we find in the BUI file (attached to this issue) at lines 604 and 627 that "ADJACENT" and "ADJ_SURF" are empty:
```
line 604: FLOOR =c_000019             : SURF=   59 : AREA=     236.881 : ADJACENT= : ADJ_SURF= :  : GEOSURF=0.102000

line 627: CEILING=c_000017             : SURF=   81 : AREA=     236.881 : ADJACENT= : ADJ_SURF= : 
```
 Whereas in line 604 it should be:
```
line 604: FLOOR =c_000019             : SURF=   59 : AREA=     236.881 : ADJACENT=z_000001 : ADJ_SURF=81 :  : GEOSURF=0.102000
```
And line 627:
```
line 627: CEILING=c_000017             : SURF=   81 : AREA=     236.881 : ADJACENT=z_000002 : ADJ_SURF=59 : 
```

Moreover, we do not understand why this kind of error happens while for other adjacent walls there is no errors, for example line 602 and 625 of the file: 
```
line 602: WALL  =c_000021             : SURF=   57 : AREA=     110.544 : ADJACENT=z_000001 : ADJ_SURF=79 : FRONT : GEOSURF=0.034000

line 625: WALL  =c_000021             : SURF=   79 : AREA=     110.544 : ADJACENT=z_000002 : ADJ_SURF=57 : BACK : GEOSURF=0.147827
```

[T3D_NECB 2011 - Warehouse_NOT WORKING.zip](https://github.com/samuelduchesne/archetypal/files/3184026/T3D_NECB.2011.-.Warehouse_NOT.WORKING.zip)

**Comment by louisleroy5** [comment]
Update: Partially solve by forcing adjacent walls to have the same construction. There is still some errors:
- still "adajcent" errors in the NECB Hospital, MidRise Apartment and Outpatient IDF files: adjacencies not found (we do not know why).
- when running a simulation (e.g. max heat load calculation) in TRNSYS, 3 buildings (HighRise Apt., Secondary School and Small Hotel) raise Error 306: "Illegal FORMAT specification given" (see attached file please).
[T3D__maxheatload.log](https://github.com/samuelduchesne/archetypal/files/3188305/T3D__maxheatload.log)

**Comment by samuelduchesne** [comment]
c95fe92 fixes this issue
