### ISSUE TITLE
ar.settings paths do not refer to the paths given in conftest

### ISSUE THREAD

**Issue by louisleroy5** [samuelduchesne/archetypal#2]
ar.settings paths do not refer to the paths given in config. For Example :

ar.settings.data_folder returns 'data' instead of 'tests/temp/data'

The same problem happens for ar.settings.imgs_folder ; ar.settings.cache_folder ; ar.settings.logs_folder.

**Comment by louisleroy5** [comment]
After several tests, the issue seems to only happen when running the parallel_process()

**Comment by samuelduchesne** [comment]
Thanks, I don't quite understand why this happens. We need to investigate...

**Comment by samuelduchesne** [comment]
I just checked this on 890be44b6cd3f874d9fa150929b838e74ff170a2 and everything seems working fine. Closing now.
