### ISSUE TITLE
EnergyPlus Version issue

### ISSUE THREAD

**Issue by zberzolla** [samuelduchesne/archetypal#336]
[issueFiles.zip](https://github.com/samuelduchesne/archetypal/files/8904109/issueFiles.zip)
When running through Archetypal these IDFs are E+ v=9.5 and it gives an error that it wants v=9.2. Using as-version also does not work.

**Comment by samuelduchesne** [comment]
Hi @zberzolla! No issues on my end:
![image](https://user-images.githubusercontent.com/22966009/174665516-9c9c19b1-5d1c-49bb-b5e4-1af25c9b640d.png)

Silly question, but do you have EnergyPlus 9.5 (or above) installed? I have all these:
![image](https://user-images.githubusercontent.com/22966009/174665619-8cf54ca8-30f6-4c38-88ac-95c39c14e455.png)

**Comment by samuelduchesne** [comment]
Also, the first file "MultiFamily2015_Gas_3A.idf" does not even run with Ep-Launch. I think somehow ExpandObjects has already been run for this file to create the basement preprocessor objects (See all the components that are commented out with a `!`) but some of the objects are missing.

**Comment by zberzolla** [comment]
I have up to (and including 9-5) installed, just not 9-6. But maybe it’s the other issue, I can start with a fresh file and try that.

Zach
