### ISSUE TITLE
BostonTemplateLibrary_2.json incorrectly stores windows

### ISSUE THREAD

**Issue by szvsw** [samuelduchesne/archetypal#377]
It stores the complete dict of windows, rather than a ref:
https://github.com/samuelduchesne/archetypal/blob/66dc6dc2a697da62e60dc81f5e8fbe3ee7181012/tests/input_data/umi_samples/BostonTemplateLibrary_2.json#L5487-L5538

This means that when loading building templates, it will create a new window object every time, since L336 will always error out:

https://github.com/samuelduchesne/archetypal/blob/66dc6dc2a697da62e60dc81f5e8fbe3ee7181012/archetypal/template/building_template.py#L335-L341

This is normally handled fine, but in the realtime-graphs setup that I am working on right now, this leads to errors.  

I'm pretty sure it's just an artifact of an old call to `save()` a template library, since current template libraries appear to save windows at the building template layer as refs, so it's just a matter of fixing the json.

**Comment by szvsw** [comment]
As a follow-up, I notice that `BostonTemplateLibrary_nodup.json` *does* store windows as refs, so perhaps this is intentional and `BostonTemplateLibrary_2.json` is meant to store nested objects for testing purposes - if so, is this considered a supported format for a serialized template library?

**Comment by szvsw** [comment]
Alright, I was able to set up try catch handling to deal with the case that I am working on, but still would like to make sure that it is valid to store nested objects in a template lib serialization.

**Comment by samuelduchesne** [comment]
For reference, objects should not be stored in a nested way. BostonTemplateLibrary_2.json is an example of a library ad returned by the UMI Template Editor. I believe there is a bug in there which creates nested WindowSetting in each BuildingTemblate object and adds a ref in the WindowSettings array. That should not be the case in our implementation of the serializer
