### ISSUE TITLE
In IDF reduction, attic's contructions should not be ignored

### ISSUE THREAD

**Issue by louisleroy5** [samuelduchesne/archetypal#39]
When reducing an IDF file, we ignore the attic characterictics.
Problem: for the roof, the attic construction should be used! Now, it is the ceiling construction that is used for the roof (usually less insulated than a roof construction).

**Comment by samuelduchesne** [comment]
fixed by ea06288fc15f0d5a4ba4a072dec53e9dcf2684a9
