### ISSUE TITLE
[Request] Document conda installation workflow

### ISSUE THREAD

**Issue by brynpickering** [samuelduchesne/archetypal#42]
Installing on MacOS fails to complete due to a pip wheel not being found for 'regex' (one of the dependencies of a dependency). This isn't an issue with archetypal, per se, but was solved by a conda installation workflow (i.e. creating a conda environment, installing all dependencies from conda / conda forge, then installing archetypal with pip). Would it be possible to:

a) have a working conda environment requirements file in this repository, to minimise direct pip dependency, and

b) update the docs to include information on installing archetypal using a conda workflow, instead of directly with pip?

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/1833)

Edit: I see there is already a requirements file, which is used in the Docker instance, but it would need updating to work with MacOS too...

**Comment by samuelduchesne** [comment]
Hi @brynpickering, as per 9c094567429d2a95bbeccbab9da2ecc18798f217, I believe this can be closed

**Comment by brynpickering** [comment]
Seems to make sense from reading the file changes in the commit, but would be good to see online too. When's the planned next release?

**Comment by samuelduchesne** [comment]
oh! I forgot to say that the “develop” branch is also built on readthedocs. 
![archetypal 1 3 0 — archetypal 1 3 0 documentation](https://user-images.githubusercontent.com/22966009/74442846-3870a000-4e40-11ea-832d-065f4fb34806.png)
