### ISSUE TITLE
[Request] Better management of EnergyPlus dependency

### ISSUE THREAD

**Issue by brynpickering** [samuelduchesne/archetypal#43]
The docs specify E+ v.8.9.0, when v.9.2.0 is already available (I can safely say that `archetypal` doesn't work with v.9.2.0!). Version issues crop up relatively late on in the use of `archetypal`, and are not particularly explicit in providing advice on how to solve them in the error messages. Could you check for E+ version on python interactive import of `archetypal`, then raise errors then about any user E+ version issues, instead of waiting for one of the `archetypal` functions to fail later on? It might also help to make the version dependency even more explicit in e.g. the package README.

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/1833)

**Comment by samuelduchesne** [comment]
Hi @brynpickering, you are right that E+ version handling is more or less patchy at the moment. It has been a goal for us to try to handle as much as possible version compatibility issues. This is why, for instance, archetypal tries to upgrade the idf file (if it is older than any installed E+ versions) before launching E+. 

Then again, it makes me wonder what is the best path forward. Should `eppy` handle versions of energy plus natively? Or should `archetypal` continue to patch such functionalities? I would be interested in having your thoughts on that.

Anyhow, let us add a more explicit error handling and provide advice on how to solve them, as you suggest. For example, the `idflcass.idf_version_updater` does not handle well missing transitioning files at the moment, if I remember correctly; this should be addressed as well.

## Issue pathways
To organize this particular issue, I see the following use cases that need a closer look:
- [ ] User runs archetypal without any EnergyPlus installs
- [ ] User runs archetypal with an idf file older than the available install
- [ ] User runs archetypal with an idf file newer than the available install
- [ ] User runs archetypal with more than one version of E+ installed on their machine; which one should be used?

**Comment by brynpickering** [comment]
PR looks like it addresses most of the concerns I raised, and the use cases you mention in your comment are those that I agree should be addressed. In addition I would include 'User runs archetypal with an idf file older than the available install, but available install is newer than we have accounted for in our conversion scripts' (i.e. the case where I tried to use v9.2.0 before you updated the code with #49). Also, could you have a test that runs for each of these use cases as part of your continuous integration?

**Comment by samuelduchesne** [comment]
Yes, It's possible to test other EnergyPlus versions in the CI. Let me see how I can implement this. I'll add your suggestion to the series of tests.

**Comment by samuelduchesne** [comment]
Since #58, the package requirement is EnergyPlus 9.2.0 and above. This simplifies a lot of things. The documentation reflects this in 2191ec00175310b9f35e2f9e53e55a902c2a0892

**Comment by samuelduchesne** [comment]
Hi @brynpickering, I think this can be closed.

**Comment by brynpickering** [comment]
Looks good to me!
