### ISSUE TITLE
Tests failing on MacOS

### ISSUE THREAD

**Issue by brynpickering** [samuelduchesne/archetypal#45]
8 tests fail and 22 error when running tests locally on MacOS. The 22 errors seem to all be trnsys related, but could be handled more gracefully by skipping a test if the operating system is not Windows (see [here](http://doc.pytest.org/en/latest/skipping.html)). Full test log is given [here](https://gist.github.com/brynpickering/569274c474813f72e6730e35f3d5ad99) - enjoy!

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/1833)

**Comment by samuelduchesne** [comment]
Hi @brynpickering, as per your suggestion, I added skips for macOS builds (see #53). This pull request also added a macOS CI (using Travis). I believe this can be closed.

**Comment by brynpickering** [comment]
Great! Something to consider is moving CI to Azure pipelines, as it is currently better maintained than Travis (for reference, we recently moved to it in [our project](https://github.com/calliope-project/calliope/commit/4d7d5047a5c45d55aa937ffa6058579f4fb573e5)).
