### ISSUE TITLE
JOSS paper review

### ISSUE THREAD

**Issue by brynpickering** [samuelduchesne/archetypal#47]
Just two points on your JOSS paper (otherwise, I think it is sufficiently clear):

1. Line 62: striped -> stripped

2. Lines 79-81: Could you add links to the references to DOE benchmark models, to allow interested users to easily access those models?

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/1833)

**Comment by samuelduchesne** [comment]
Easy enough 😉

Added links to the references themselves. Is that what you meant @brynpickering ?

Should I close this issue now as other paper-related issues could be handled in issue #41

**Comment by brynpickering** [comment]
Yes, happy for this to be closed. Although. I would first check the most recently built paper PDF, there seems to be some issue with the USDOE reference in the main text.

**Comment by samuelduchesne** [comment]
Good catch! Latest PDF looks good now.
